name: Build Docker Image for Linux ARM

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '*'

jobs:
  build-linux-arm:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [ARM64]
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/golang.Dockerfile
          tags: ${{ secrets.REGISTRY_USERNAME }}/go-whatsapp-web-multidevice:latest, ${{ secrets.REGISTRY_USERNAME }}/go-whatsapp-web-multidevice:${{ github.ref_name }}